# TODO: latexify
all:
	mkdir -p ../build/docs
	pdflatex -interaction nonstopmode gp4-hdl.tex -output-directory ../build/docs
	pdflatex -interaction nonstopmode gp4-hdl.tex -output-directory ../build/docs
